language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    sources:
    - sourceline: 'ppa:git-core/ppa'
    packages:
    - git-lfs

install:
  git lfs install

cache:
  - cargo
